;/*FB_PKG_DELIM*/

/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 *
 * @fullSyntaxTransform
 * @generated
 * @noflow
 * @nolint
 * @oncall lexical_web_text_editor
 * @preserve-invariant-messages
 * @preserve-whitespace
 * @preventMunge
 */__d("LexicalList.prod",["Lexical","LexicalUtils"],(function $module_LexicalList_prod(global,require,requireDynamic,requireLazy,module,exports){

'use strict';var l;function n(a){var b=new URLSearchParams();b.append("code",a);for(var c=1;c<arguments.length;c++){b.append("v",arguments[c]);}throw Error("Minified Lexical error #"+a+"; visit https://lexical.dev/docs/error?"+b+" for the full message or "+"use the non-minified dev environment for full errors and additional helpful warnings.");}l=n&&n.__esModule&&Object.prototype.hasOwnProperty.call(n,"default")?n["default"]:n;
function p(a){var b=1;for(a=a.getParent();null!=a;){if(q(a)){a=a.getParent();if(r(a)){b++;a=a.getParent();continue;}l(40);}break;}return b;}function t(a){a=a.getParent();r(a)||l(40);var b=a;for(;null!==b;){b=b.getParent(),r(b)&&(a=b);}return a;}function u(a){var b=[];a=a.getChildren().filter(q);for(var c=0;c<a.length;c++){var d=a[c],e=d.getFirstChild();r(e)?b=b.concat(u(e)):b.push(d);}return b;}function v(a){return q(a)&&r(a.getFirstChild());}
function w(a){for(;null==a.getNextSibling()&&null==a.getPreviousSibling();){var b=a.getParent();if(null==b||!q(a)&&!r(a))break;a=b;}a.remove();}function x(a){return y().append(a);}function z(a,b){return q(a)&&(0===b.length||1===b.length&&a.is(b[0])&&0===a.getChildrenSize());}
function A(a,b){a.update(function(){var c=require("Lexical").$getSelection();if(null!==c){var d=c.getNodes();if(require("Lexical").$isRangeSelection(c)){c=c.getStartEndPoints();null===c&&l(143);var _c=c;c=_c[0];c=c.getNode();var e=c.getParent();if(z(c,d)){d=B(b);require("Lexical").$isRootOrShadowRoot(e)?(c.replace(d),e=y(),require("Lexical").$isElementNode(c)&&(e.setFormat(c.getFormatType()),e.setIndent(c.getIndent())),d.append(e)):q(c)&&(c=c.getParentOrThrow(),E(d,c.getChildren()),c.replace(d));return;}}c=new Set();for(e=0;e<d.length;e++){var f=d[e];if(require("Lexical").$isElementNode(f)&&f.isEmpty()&&
!q(f)&&!c.has(f.getKey()))F(f,b);else if(require("Lexical").$isLeafNode(f))for(f=f.getParent();null!=f;){var m=f.getKey();if(r(f)){if(!c.has(m)){var k=B(b);E(k,f.getChildren());f.replace(k);c.add(m);}break;}else{k=f.getParent();if(require("Lexical").$isRootOrShadowRoot(k)&&!c.has(m)){c.add(m);F(f,b);break;}f=k;}}}}});}function E(a,b){a.splice(a.getChildrenSize(),0,b);}
function F(a,b){if(r(a))return a;var c=a.getPreviousSibling(),d=a.getNextSibling(),e=y();E(e,a.getChildren());r(c)&&b===c.getListType()?(c.append(e),r(d)&&b===d.getListType()&&(E(c,d.getChildren()),d.remove()),b=c):r(d)&&b===d.getListType()?(d.getFirstChildOrThrow().insertBefore(e),b=d):(b=B(b),b.append(e),a.replace(b));e.setFormat(a.getFormatType());e.setIndent(a.getIndent());a.remove();return b;}
function G(a,b){var c=a.getLastChild();var d=b.getFirstChild();c&&d&&v(c)&&v(d)&&(G(c.getFirstChild(),d.getFirstChild()),d.remove());c=b.getChildren();0<c.length&&a.append.apply(a,c);b.remove();}
function H(a){a.update(function(){var b=require("Lexical").$getSelection();if(require("Lexical").$isRangeSelection(b)){var c=new Set(),d=b.getNodes(),e=b.anchor.getNode();if(z(e,d))c.add(t(e));else for(e=0;e<d.length;e++){var f=d[e];require("Lexical").$isLeafNode(f)&&(f=require("LexicalUtils").$getNearestNodeOfType(f,I),null!=f&&c.add(t(f)));}for(var _iterator=c,_isArray=Array.isArray(_iterator),_i=0,_iterator=_isArray?_iterator:_iterator[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref;if(_isArray){if(_i>=_iterator.length)break;_ref=_iterator[_i++];}else{_i=_iterator.next();if(_i.done)break;_ref=_i.value;}var k=_ref;c=k;d=u(k);for(var _iterator2=d,_isArray2=Array.isArray(_iterator2),_i2=0,_iterator2=_isArray2?_iterator2:_iterator2[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref2;if(_isArray2){if(_i2>=_iterator2.length)break;_ref2=_iterator2[_i2++];}else{_i2=_iterator2.next();if(_i2.done)break;_ref2=_i2.value;}var m=_ref2;d=require("Lexical").$createParagraphNode(),E(d,m.getChildren()),c.insertAfter(d),c=d,m.__key===b.anchor.key&&b.anchor.set(d.getKey(),0,"element"),m.__key===b.focus.key&&b.focus.set(d.getKey(),0,"element"),m.remove();}
k.remove();}}});}
function J(a){if(!v(a)){var b=a.getParent(),c=b?b.getParent():void 0,d=c?c.getParent():void 0;if(r(d)&&q(c)&&r(b)){d=b?b.getFirstChild():void 0;var e=b?b.getLastChild():void 0;if(a.is(d))c.insertBefore(a),b.isEmpty()&&c.remove();else if(a.is(e))c.insertAfter(a),b.isEmpty()&&c.remove();else{e=b.getListType();b=y();var f=B(e);b.append(f);a.getPreviousSiblings().forEach(function(k){return f.append(k);});d=y();e=B(e);d.append(e);E(e,a.getNextSiblings());c.insertBefore(b);c.insertAfter(d);c.replace(a);}}}}
function K(){var a=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(a)||!a.isCollapsed())return!1;a=a.anchor.getNode();if(!q(a)||0!==a.getChildrenSize())return!1;var b=t(a),c=a.getParent();r(c)||l(40);var d=c.getParent(),e;if(require("Lexical").$isRootOrShadowRoot(d))e=require("Lexical").$createParagraphNode(),b.insertAfter(e);else if(q(d))e=y(),d.insertAfter(e);else return!1;e.select();b=a.getNextSiblings();if(0<b.length){var f=B(c.getListType());require("Lexical").$isParagraphNode(e)?e.insertAfter(f):(c=y(),c.append(f),e.insertAfter(c));b.forEach(function(k){k.remove();
f.append(k);});}w(a);return!0;}function L(){var b=[];for(var _len=arguments.length,a=new Array(_len),_key=0;_key<_len;_key++){a[_key]=arguments[_key];}for(var _i3=0;_i3<a.length;_i3++){var c=a[_i3];if(c&&"string"===typeof c){for(var _iterator3=c.matchAll(/\S+/g),_isArray3=Array.isArray(_iterator3),_i4=0,_iterator3=_isArray3?_iterator3:_iterator3[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref4;if(_isArray3){if(_i4>=_iterator3.length)break;_ref4=_iterator3[_i4++];}else{_i4=_iterator3.next();if(_i4.done)break;_ref4=_i4.value;}var _ref5=_ref4;var d=_ref5[0];b.push(d);}}}return b;}var
I=function(_h$ElementNode){babelHelpers.inheritsLoose(I,_h$ElementNode);I.getType=function getType(){return"listitem";};I.clone=function clone(a){return new I(a.__value,a.__checked,a.__key);};function I(a,b,c){var _this;_this=_h$ElementNode.call(this,c)||this;_this.__value=void 0===a?1:a;_this.__checked=b;return _this;}var _proto=I.prototype;_proto.createDOM=function createDOM(a){var b=document.createElement("li"),c=this.getParent();r(c)&&"check"===c.getListType()&&M(b,this,null);b.value=this.__value;N(b,a.theme,this);return b;};_proto.updateDOM=function updateDOM(a,b,c){var d=this.getParent();r(d)&&"check"===d.getListType()&&M(b,this,a);b.value=this.__value;N(b,c.theme,this);return!1;};I.transform=function transform(){return function(a)
{q(a)||l(144);if(null!=a.__checked){var b=a.getParent();r(b)&&"check"!==b.getListType()&&null!=a.getChecked()&&a.setChecked(void 0);}};};I.importDOM=function importDOM(){return{li:function li(){return{conversion:O,priority:0};}};};I.importJSON=function importJSON(a){var b=y();b.setChecked(a.checked);b.setValue(a.value);b.setFormat(a.format);b.setDirection(a.direction);return b;};_proto.exportDOM=function exportDOM(a){a=this.createDOM(a._config);a.style.textAlign=this.getFormatType();return{element:a};};_proto.exportJSON=function exportJSON(){return babelHelpers["extends"]({},_h$ElementNode.prototype.exportJSON.call(this),{checked:this.getChecked(),type:"listitem",
value:this.getValue(),version:1});};_proto.append=function append(){for(var b=0;b<arguments.length;b++){var c=b<0||arguments.length<=b?undefined:arguments[b];if(require("Lexical").$isElementNode(c)&&this.canMergeWith(c)){var d=c.getChildren();this.append.apply(this,d);c.remove();}else _h$ElementNode.prototype.append.call(this,c);}return this;};_proto.replace=function replace(a,b){if(q(a))return _h$ElementNode.prototype.replace.call(this,a);this.setIndent(0);var c=this.getParentOrThrow();if(!r(c))return a;if(c.__first===this.getKey())c.insertBefore(a);else if(c.__last===this.getKey())c.insertAfter(a);else{var d=B(c.getListType()),e=this.getNextSibling();for(;e;){var f=e;e=e.getNextSibling();
d.append(f);}c.insertAfter(a);a.insertAfter(d);}b&&(require("Lexical").$isElementNode(a)||l(139),this.getChildren().forEach(function(d){a.append(d);}));this.remove();0===c.getChildrenSize()&&c.remove();return a;};_proto.insertAfter=function insertAfter(a,b){if(b===void 0){b=!0;}var c=this.getParentOrThrow();r(c)||l(39);if(q(a))return _h$ElementNode.prototype.insertAfter.call(this,a,b);var d=this.getNextSiblings();c.insertAfter(a,b);if(0!==d.length){var e=B(c.getListType());d.forEach(function(f){return e.append(f);});a.insertAfter(e,b);}return a;};_proto.remove=function remove(a){var b=this.getPreviousSibling(),c=this.getNextSibling();_h$ElementNode.prototype.remove.call(this,a);
b&&c&&v(b)&&v(c)&&(G(b.getFirstChild(),c.getFirstChild()),c.remove());};_proto.insertNewAfter=function insertNewAfter(a,b){if(b===void 0){b=!0;}a=y(null==this.__checked?void 0:!1);this.insertAfter(a,b);return a;};_proto.collapseAtStart=function collapseAtStart(a){var b=require("Lexical").$createParagraphNode();this.getChildren().forEach(function(f){return b.append(f);});var c=this.getParentOrThrow(),d=c.getParentOrThrow();var e=q(d);1===c.getChildrenSize()?e?(c.remove(),d.select()):(c.insertBefore(b),c.remove(),c=a.anchor,a=a.focus,d=b.getKey(),"element"===c.type&&c.getNode().is(this)&&c.set(d,c.offset,"element"),
"element"===a.type&&a.getNode().is(this)&&a.set(d,a.offset,"element")):(c.insertBefore(b),this.remove());return!0;};_proto.getValue=function getValue(){return this.getLatest().__value;};_proto.setValue=function setValue(a){this.getWritable().__value=a;};_proto.getChecked=function getChecked(){var a=this.getLatest(),b,c=this.getParent();r(c)&&(b=c.getListType());return"check"===b?!!a.__checked:void 0;};_proto.setChecked=function setChecked(a){this.getWritable().__checked=a;};_proto.toggleChecked=function toggleChecked(){this.setChecked(!this.__checked);};_proto.getIndent=function getIndent(){var a=this.getParent();if(null===a)return this.getLatest().__indent;a=a.getParentOrThrow();
var b=0;for(;q(a);){a=a.getParentOrThrow().getParentOrThrow(),b++;}return b;};_proto.setIndent=function setIndent(a){"number"!==typeof a&&l(117);a=Math.floor(a);0<=a||l(199);var b=this.getIndent();for(;b!==a;){if(b<a){var c=new Set();if(!v(this)&&!c.has(this.getKey())){var d=this.getParent(),e=this.getNextSibling(),f=this.getPreviousSibling();if(v(e)&&v(f))d=f.getFirstChild(),r(d)&&(d.append(this),f=e.getFirstChild(),r(f)&&(f=f.getChildren(),E(d,f),e.remove(),c.add(e.getKey())));else if(v(e))e=e.getFirstChild(),r(e)&&(e=e.getFirstChild(),
null!==e&&e.insertBefore(this));else if(v(f))e=f.getFirstChild(),r(e)&&e.append(this);else if(r(d)){c=y();var k=B(d.getListType());c.append(k);k.append(this);f?f.insertAfter(c):e?e.insertBefore(c):d.append(c);}}b++;}else J(this),b--;}return this;};_proto.canInsertAfter=function canInsertAfter(a){return q(a);};_proto.canReplaceWith=function canReplaceWith(a){return q(a);};_proto.canMergeWith=function canMergeWith(a){return require("Lexical").$isParagraphNode(a)||q(a);};_proto.extractWithChild=function extractWithChild(a,b){if(!require("Lexical").$isRangeSelection(b))return!1;a=b.anchor.getNode();var c=b.focus.getNode();return this.isParentOf(a)&&this.isParentOf(c)&&
this.getTextContent().length===b.getTextContent().length;};_proto.isParentRequired=function isParentRequired(){return!0;};_proto.createParentElementNode=function createParentElementNode(){return B("bullet");};_proto.canMergeWhenEmpty=function canMergeWhenEmpty(){return!0;};return I;}(require("Lexical").ElementNode);
function N(a,b,c){var d=[],e=[];var f=(b=b.list)?b.listitem:void 0;if(b&&b.nested)var k=b.nested.listitem;void 0!==f&&d.push.apply(d,L(f));if(b){f=c.getParent();f=r(f)&&"check"===f.getListType();var m=c.getChecked();f&&!m||e.push(b.listitemUnchecked);f&&m||e.push(b.listitemChecked);f&&d.push(m?b.listitemChecked:b.listitemUnchecked);}void 0!==k&&(k=L(k),c.getChildren().some(function(m){return r(m);})?d.push.apply(d,k):e.push.apply(e,k));0<e.length&&require("LexicalUtils").removeClassNamesFromElement.apply(require("LexicalUtils"),[a].concat(e));0<d.length&&require("LexicalUtils").addClassNamesToElement.apply(require("LexicalUtils"),[a].concat(d));}
function M(a,b,c){r(b.getFirstChild())?(a.removeAttribute("role"),a.removeAttribute("tabIndex"),a.removeAttribute("aria-checked")):(a.setAttribute("role","checkbox"),a.setAttribute("tabIndex","-1"),c&&b.__checked===c.__checked||a.setAttribute("aria-checked",b.getChecked()?"true":"false"));}
function O(a){if(a.classList.contains("task-list-item")){for(var _iterator4=a.children,_isArray4=Array.isArray(_iterator4),_i5=0,_iterator4=_isArray4?_iterator4:_iterator4[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref6;if(_isArray4){if(_i5>=_iterator4.length)break;_ref6=_iterator4[_i5++];}else{_i5=_iterator4.next();if(_i5.done)break;_ref6=_i5.value;}var b=_ref6;if("INPUT"===b.tagName)return a=b,"checkbox"!==a.getAttribute("type")?a={node:null}:(a=a.hasAttribute("checked"),a={node:y(a)}),a;}}a=a.getAttribute("aria-checked");return{node:y("true"===a?!0:"false"===a?!1:void 0)};}function y(a){return require("Lexical").$applyNodeReplacement(new I(void 0,a));}function q(a){return a instanceof I;}var
P=function(_h$ElementNode2){babelHelpers.inheritsLoose(P,_h$ElementNode2);P.getType=function getType(){return"list";};P.clone=function clone(a){return new P(a.__listType||S[a.__tag],a.__start,a.__key);};function P(a,b,c){var _this2;_this2=_h$ElementNode2.call(this,c)||this;_this2.__listType=a=S[a]||a;_this2.__tag="number"===a?"ol":"ul";_this2.__start=b;return _this2;}var _proto2=P.prototype;_proto2.getTag=function getTag(){return this.__tag;};_proto2.setListType=function setListType(a){var b=this.getWritable();b.__listType=a;b.__tag="number"===a?"ol":"ul";};_proto2.getListType=function getListType(){return this.__listType;};_proto2.getStart=function getStart(){return this.__start;};_proto2.createDOM=function createDOM(a){var b=document.createElement(this.__tag);1!==this.__start&&b.setAttribute("start",
String(this.__start));b.__lexicalListType=this.__listType;T(b,a.theme,this);return b;};_proto2.updateDOM=function updateDOM(a,b,c){if(a.__tag!==this.__tag)return!0;T(b,c.theme,this);return!1;};P.transform=function transform(){return function(a){r(a)||l(163);var b=a.getNextSibling();r(b)&&a.getListType()===b.getListType()&&G(a,b);b="check"!==a.getListType();var c=a.getStart();for(var _iterator5=a.getChildren(),_isArray5=Array.isArray(_iterator5),_i6=0,_iterator5=_isArray5?_iterator5:_iterator5[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref7;if(_isArray5){if(_i6>=_iterator5.length)break;_ref7=_iterator5[_i6++];}else{_i6=_iterator5.next();if(_i6.done)break;_ref7=_i6.value;}var d=_ref7;q(d)&&(d.getValue()!==c&&d.setValue(c),b&&null!=d.getLatest().__checked&&d.setChecked(void 0),r(d.getFirstChild())||c++);}};};P.importDOM=function importDOM(){return{ol:function ol(){return(
{conversion:U,priority:0});},ul:function ul(){return{conversion:U,priority:0};}};};P.importJSON=function importJSON(a){var b=B(a.listType,a.start);b.setFormat(a.format);b.setIndent(a.indent);b.setDirection(a.direction);return b;};_proto2.exportDOM=function exportDOM(a){(a=this.createDOM(a._config,a))&&require("LexicalUtils").isHTMLElement(a)&&(1!==this.__start&&a.setAttribute("start",String(this.__start)),"check"===this.__listType&&a.setAttribute("__lexicalListType","check"));return{element:a};};_proto2.exportJSON=function exportJSON(){return babelHelpers["extends"]({},_h$ElementNode2.prototype.exportJSON.call(this),{listType:this.getListType(),start:this.getStart(),
tag:this.getTag(),type:"list",version:1});};_proto2.canBeEmpty=function canBeEmpty(){return!1;};_proto2.canIndent=function canIndent(){return!1;};_proto2.append=function append(){for(var c=0;c<arguments.length;c++){var b=c<0||arguments.length<=c?undefined:arguments[c];if(q(b))_h$ElementNode2.prototype.append.call(this,b);else{var d=y();r(b)?d.append(b):require("Lexical").$isElementNode(b)?(b=require("Lexical").$createTextNode(b.getTextContent()),d.append(b)):d.append(b);_h$ElementNode2.prototype.append.call(this,d);}}return this;};_proto2.extractWithChild=function extractWithChild(a){return q(a);};return P;}(require("Lexical").ElementNode);
function T(a,b,c){var d=[],e=[];var f=b.list;if(void 0!==f){var m=f[c.__tag+"Depth"]||[];b=p(c)-1;var Q=b%m.length;var k=m[Q];var R=f[c.__tag],C,D=f.nested;f=f.checklist;void 0!==D&&D.list&&(C=D.list);void 0!==R&&d.push(R);void 0!==f&&"check"===c.__listType&&d.push(f);if(void 0!==k)for(d.push.apply(d,L(k)),k=0;k<m.length;k++){k!==Q&&e.push(c.__tag+k);}void 0!==C&&(c=L(C),1<b?d.push.apply(d,c):e.push.apply(e,c));}0<e.length&&require("LexicalUtils").removeClassNamesFromElement.apply(require("LexicalUtils"),[a].concat(e));0<d.length&&require("LexicalUtils").addClassNamesToElement.apply(require("LexicalUtils"),[a].concat(d));}
function V(a){var b=[];for(var d=0;d<a.length;d++){var c=a[d];q(c)?(b.push(c),c=c.getChildren(),1<c.length&&c.forEach(function(e){r(e)&&b.push(x(e));})):b.push(x(c));}return b;}
function U(a){var b=a.nodeName.toLowerCase(),c=null;if("ol"===b)c=B("number",a.start);else if("ul"===b){a:if("check"===a.getAttribute("__lexicallisttype")||a.classList.contains("contains-task-list"))a=!0;else{for(var _iterator6=a.childNodes,_isArray6=Array.isArray(_iterator6),_i7=0,_iterator6=_isArray6?_iterator6:_iterator6[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref8;if(_isArray6){if(_i7>=_iterator6.length)break;_ref8=_iterator6[_i7++];}else{_i7=_iterator6.next();if(_i7.done)break;_ref8=_i7.value;}var d=_ref8;if(require("LexicalUtils").isHTMLElement(d)&&d.hasAttribute("aria-checked")){a=!0;break a;}}a=!1;}c=a?B("check"):B("bullet");}return{after:V,node:c};}var S={ol:"number",ul:"bullet"};function B(a,b){if(b===void 0){b=1;}return require("Lexical").$applyNodeReplacement(new P(a,b));}function r(a){return a instanceof P;}
var W=require("Lexical").createCommand("INSERT_UNORDERED_LIST_COMMAND"),X=require("Lexical").createCommand("INSERT_ORDERED_LIST_COMMAND"),Y=require("Lexical").createCommand("INSERT_CHECK_LIST_COMMAND"),Z=require("Lexical").createCommand("REMOVE_LIST_COMMAND");exports.$createListItemNode=y;exports.$createListNode=B;exports.$getListDepth=p;exports.$handleListInsertParagraph=K;exports.$isListItemNode=q;exports.$isListNode=r;exports.INSERT_CHECK_LIST_COMMAND=Y;exports.INSERT_ORDERED_LIST_COMMAND=X;exports.INSERT_UNORDERED_LIST_COMMAND=W;exports.ListItemNode=I;
exports.ListNode=P;exports.REMOVE_LIST_COMMAND=Z;exports.insertList=A;exports.registerList=function(a){var _require_Lexical;return require("LexicalUtils").mergeRegister(a.registerCommand(X,function(){A(a,"number");return!0;},(_require_Lexical=require("Lexical")).COMMAND_PRIORITY_LOW),a.registerCommand(W,function(){A(a,"bullet");return!0;},_require_Lexical.COMMAND_PRIORITY_LOW),a.registerCommand(Z,function(){H(a);return!0;},_require_Lexical.COMMAND_PRIORITY_LOW),a.registerCommand(_require_Lexical.INSERT_PARAGRAPH_COMMAND,function(){return K()?!0:!1;},_require_Lexical.COMMAND_PRIORITY_LOW));};exports.removeList=H;}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 *
 * @fullSyntaxTransform
 * @generated
 * @noflow
 * @nolint
 * @oncall lexical_web_text_editor
 * @preserve-invariant-messages
 * @preserve-whitespace
 * @preventMunge
 */__d("LexicalRichText.prod",["Lexical","LexicalClipboard","LexicalSelection","LexicalUtils","regeneratorRuntime"],(function $module_LexicalRichText_prod(global,require,requireDynamic,requireLazy,module,exports){

'use strict';function l(b,a){return"undefined"!==typeof document.caretRangeFromPoint?(b=document.caretRangeFromPoint(b,a),null===b?null:{node:b.startContainer,offset:b.startOffset}):"undefined"!==document.caretPositionFromPoint?(b=document.caretPositionFromPoint(b,a),null===b?null:{node:b.offsetNode,offset:b.offset}):null;}
var n="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement,p=n&&"documentMode"in document?document.documentMode:null,q=n&&"InputEvent"in window&&!p?"getTargetRanges"in new window.InputEvent("input"):!1,r=n&&/Version\/[\d.]+.*Safari/.test(navigator.userAgent),t=n&&/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream,v=n&&/^(?=.*Chrome).*/i.test(navigator.userAgent),w=n&&/AppleWebKit\/[\d.]+/.test(navigator.userAgent)&&!v,x=
require("Lexical").createCommand("DRAG_DROP_PASTE_FILE");var
y=function(_k$ElementNode){babelHelpers.inheritsLoose(y,_k$ElementNode);y.getType=function getType(){return"quote";};y.clone=function clone(b){return new y(b.__key);};function y(b){return _k$ElementNode.call(this,b)||this;}var _proto=y.prototype;_proto.createDOM=function createDOM(b){var a=document.createElement("blockquote");require("LexicalUtils").addClassNamesToElement(a,b.theme.quote);return a;};_proto.updateDOM=function updateDOM(){return!1;};y.importDOM=function importDOM(){return{blockquote:function blockquote(){return{conversion:z,priority:0};}};};_proto.exportDOM=function exportDOM(b){var _k$ElementNode$protot=_k$ElementNode.prototype.exportDOM.call(this,b);b=_k$ElementNode$protot.element;if(b&&require("LexicalUtils").isHTMLElement(b)){this.isEmpty()&&b.append(document.createElement("br"));var a=this.getFormatType();b.style.textAlign=a;if(a=this.getDirection())b.dir=
a;}return{element:b};};y.importJSON=function importJSON(b){var a=A();a.setFormat(b.format);a.setIndent(b.indent);a.setDirection(b.direction);return a;};_proto.exportJSON=function exportJSON(){return babelHelpers["extends"]({},_k$ElementNode.prototype.exportJSON.call(this),{type:"quote"});};_proto.insertNewAfter=function insertNewAfter(b,a){b=require("Lexical").$createParagraphNode();var d=this.getDirection();b.setDirection(d);this.insertAfter(b,a);return b;};_proto.collapseAtStart=function collapseAtStart(){var b=require("Lexical").$createParagraphNode();this.getChildren().forEach(function(a){return b.append(a);});this.replace(b);return!0;};_proto.canMergeWhenEmpty=function canMergeWhenEmpty(){return!0;};return y;}(require("Lexical").ElementNode);
function A(){return require("Lexical").$applyNodeReplacement(new y());}var
C=function(_k$ElementNode2){babelHelpers.inheritsLoose(C,_k$ElementNode2);C.getType=function getType(){return"heading";};C.clone=function clone(b){return new C(b.__tag,b.__key);};function C(b,a){var _this;_this=_k$ElementNode2.call(this,a)||this;_this.__tag=b;return _this;}var _proto2=C.prototype;_proto2.getTag=function getTag(){return this.__tag;};_proto2.createDOM=function createDOM(b){var a=this.__tag,d=document.createElement(a);b=b.theme.heading;void 0!==b&&require("LexicalUtils").addClassNamesToElement(d,b[a]);return d;};_proto2.updateDOM=function updateDOM(){return!1;};C.importDOM=function importDOM(){return{h1:function h1(){return{conversion:D,priority:0};},h2:function h2(){return{conversion:D,priority:0};},h3:function h3(){return{conversion:D,priority:0};},h4:function h4(){return{conversion:D,priority:0};},h5:function h5(){return{conversion:D,
priority:0};},h6:function h6(){return{conversion:D,priority:0};},p:function p(b){b=b.firstChild;return null!==b&&E(b)?{conversion:function conversion(){return{node:null};},priority:3}:null;},span:function span(b){return E(b)?{conversion:function conversion(){return{node:F("h1")};},priority:3}:null;}};};_proto2.exportDOM=function exportDOM(b){var _k$ElementNode2$proto=_k$ElementNode2.prototype.exportDOM.call(this,b);b=_k$ElementNode2$proto.element;if(b&&require("LexicalUtils").isHTMLElement(b)){this.isEmpty()&&b.append(document.createElement("br"));var a=this.getFormatType();b.style.textAlign=a;if(a=this.getDirection())b.dir=a;}return{element:b};};C.importJSON=function importJSON(b){var a=F(b.tag);a.setFormat(b.format);a.setIndent(b.indent);
a.setDirection(b.direction);return a;};_proto2.exportJSON=function exportJSON(){return babelHelpers["extends"]({},_k$ElementNode2.prototype.exportJSON.call(this),{tag:this.getTag(),type:"heading",version:1});};_proto2.insertNewAfter=function insertNewAfter(b,a){if(a===void 0){a=!0;}var d=b?b.anchor.offset:0;var e=this.getLastDescendant();e=!e||b&&b.anchor.key===e.getKey()&&d===e.getTextContentSize()||!b?require("Lexical").$createParagraphNode():F(this.getTag());var f=this.getDirection();e.setDirection(f);this.insertAfter(e,a);0===d&&!this.isEmpty()&&b&&(b=require("Lexical").$createParagraphNode(),b.select(),this.replace(b,!0));return e;};_proto2.collapseAtStart=function collapseAtStart(){var b=this.isEmpty()?
require("Lexical").$createParagraphNode():F(this.getTag());this.getChildren().forEach(function(a){return b.append(a);});this.replace(b);return!0;};_proto2.extractWithChild=function extractWithChild(){return!0;};return C;}(require("Lexical").ElementNode);function E(b){return"span"===b.nodeName.toLowerCase()?"26pt"===b.style.fontSize:!1;}function D(b){var a=b.nodeName.toLowerCase(),d=null;if("h1"===a||"h2"===a||"h3"===a||"h4"===a||"h5"===a||"h6"===a)d=F(a),null!==b.style&&(require("Lexical").setNodeIndentFromDOM(b,d),d.setFormat(b.style.textAlign));return{node:d};}
function z(b){var a=A();null!==b.style&&(a.setFormat(b.style.textAlign),require("Lexical").setNodeIndentFromDOM(b,a));return{node:a};}function F(b){return require("Lexical").$applyNodeReplacement(new C(b));}function G(b,a){b.preventDefault();a.update(function(){var d=require("Lexical").$getSelection(),e=require("LexicalUtils").objectKlassEquals(b,InputEvent)||require("LexicalUtils").objectKlassEquals(b,KeyboardEvent)?null:b.clipboardData;null!=e&&null!==d&&require("LexicalClipboard").$insertDataTransferForRichText(e,d,a);},{tag:"paste"});}
function H(b,a){return require("regeneratorRuntime").async(function H$(_context){while(1){switch(_context.prev=_context.next){case 0:_context.next=2;return require("regeneratorRuntime").awrap(require("LexicalClipboard").copyToClipboard(a,require("LexicalUtils").objectKlassEquals(b,ClipboardEvent)?b:null));case 2:a.update(function(){var d=require("Lexical").$getSelection();require("Lexical").$isRangeSelection(d)?d.removeText():require("Lexical").$isNodeSelection(d)&&d.getNodes().forEach(function(e){return e.remove();});});case 3:case"end":return _context.stop();}}},null,this);}
function I(b){var a=null;require("LexicalUtils").objectKlassEquals(b,DragEvent)?a=b.dataTransfer:require("LexicalUtils").objectKlassEquals(b,ClipboardEvent)&&(a=b.clipboardData);if(null===a)return[!1,[],!1];var d=a.types;b=d.includes("Files");d=d.includes("text/html")||d.includes("text/plain");return[b,Array.from(a.files),d];}
function J(b){var a=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(a))return!1;var d=new Set();a=a.getNodes();for(var m=0;m<a.length;m++){var e=a[m],f=e.getKey();d.has(f)||(e=require("LexicalUtils").$findMatchingParent(e,function(u){return require("Lexical").$isElementNode(u)&&!u.isInline();}),null!==e&&(f=e.getKey(),e.canIndent()&&!d.has(f)&&(d.add(f),b(e))));}return 0<d.size;}function K(b){b=require("Lexical").$getNearestNodeFromDOMNode(b);return require("Lexical").$isDecoratorNode(b);}exports.$createHeadingNode=F;exports.$createQuoteNode=A;
exports.$isHeadingNode=function(b){return b instanceof C;};exports.$isQuoteNode=function(b){return b instanceof y;};exports.DRAG_DROP_PASTE=x;exports.HeadingNode=C;exports.QuoteNode=y;exports.eventFiles=I;
exports.registerRichText=function(b){var _require_Lexical;return require("LexicalUtils").mergeRegister(b.registerCommand((_require_Lexical=require("Lexical")).CLICK_COMMAND,function(){var a=require("Lexical").$getSelection();return require("Lexical").$isNodeSelection(a)?(a.clear(),!0):!1;},0),b.registerCommand(_require_Lexical.DELETE_CHARACTER_COMMAND,function(a){var d=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(d))return!1;d.deleteCharacter(a);return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.DELETE_WORD_COMMAND,function(a){var d=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(d))return!1;d.deleteWord(a);return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),
b.registerCommand(_require_Lexical.DELETE_LINE_COMMAND,function(a){var d=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(d))return!1;d.deleteLine(a);return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.CONTROLLED_TEXT_INSERTION_COMMAND,function(a){var d=require("Lexical").$getSelection();if("string"===typeof a)null!==d&&d.insertText(a);else{if(null===d)return!1;var e=a.dataTransfer;null!=e?require("LexicalClipboard").$insertDataTransferForRichText(e,d,b):require("Lexical").$isRangeSelection(d)&&(a=a.data)&&d.insertText(a);}return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.REMOVE_TEXT_COMMAND,
function(){var a=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(a))return!1;a.removeText();return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.FORMAT_TEXT_COMMAND,function(a){var d=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(d))return!1;d.formatText(a);return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.FORMAT_ELEMENT_COMMAND,function(a){var d=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(d)&&!require("Lexical").$isNodeSelection(d))return!1;d=d.getNodes();for(var _iterator=d,_isArray=Array.isArray(_iterator),_i=0,_iterator=_isArray?_iterator:_iterator[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var _ref;if(_isArray){if(_i>=_iterator.length)break;_ref=_iterator[_i++];}else{_i=_iterator.next();if(_i.done)break;_ref=_i.value;}var e=_ref;d=require("LexicalUtils").$findMatchingParent(e,function(f){return require("Lexical").$isElementNode(f)&&!f.isInline();}),
null!==d&&d.setFormat(a);}return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.INSERT_LINE_BREAK_COMMAND,function(a){var d=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(d))return!1;d.insertLineBreak(a);return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.INSERT_PARAGRAPH_COMMAND,function(){var a=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(a))return!1;a.insertParagraph();return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.INSERT_TAB_COMMAND,function(){require("Lexical").$insertNodes([require("Lexical").$createTabNode()]);return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),
b.registerCommand(_require_Lexical.INDENT_CONTENT_COMMAND,function(){return J(function(a){var d=a.getIndent();a.setIndent(d+1);});},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.OUTDENT_CONTENT_COMMAND,function(){return J(function(a){var d=a.getIndent();0<d&&a.setIndent(d-1);});},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.KEY_ARROW_UP_COMMAND,function(a){var d=require("Lexical").$getSelection();if(require("Lexical").$isNodeSelection(d)&&!K(a.target)){if(a=d.getNodes(),0<a.length)return a[0].selectPrevious(),!0;}else if(require("Lexical").$isRangeSelection(d)&&(d=require("Lexical").$getAdjacentNode(d.focus,!0),!a.shiftKey&&require("Lexical").$isDecoratorNode(d)&&
!d.isIsolated()&&!d.isInline()))return d.selectPrevious(),a.preventDefault(),!0;return!1;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.KEY_ARROW_DOWN_COMMAND,function(a){var d=require("Lexical").$getSelection();if(require("Lexical").$isNodeSelection(d)){if(a=d.getNodes(),0<a.length)return a[0].selectNext(0,0),!0;}else if(require("Lexical").$isRangeSelection(d)){var e=d.focus;if("root"===e.key&&e.offset===require("Lexical").$getRoot().getChildrenSize())return a.preventDefault(),!0;d=require("Lexical").$getAdjacentNode(d.focus,!1);if(!a.shiftKey&&require("Lexical").$isDecoratorNode(d)&&!d.isIsolated()&&!d.isInline())return d.selectNext(),
a.preventDefault(),!0;}return!1;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.KEY_ARROW_LEFT_COMMAND,function(a){var d=require("Lexical").$getSelection();if(require("Lexical").$isNodeSelection(d)){var e=d.getNodes();if(0<e.length)return a.preventDefault(),e[0].selectPrevious(),!0;}return require("Lexical").$isRangeSelection(d)?require("LexicalSelection").$shouldOverrideDefaultCharacterSelection(d,!0)?(e=a.shiftKey,a.preventDefault(),require("LexicalSelection").$moveCharacter(d,e,!0),!0):!1:!1;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.KEY_ARROW_RIGHT_COMMAND,function(a){var d=require("Lexical").$getSelection();if(require("Lexical").$isNodeSelection(d)&&
!K(a.target)){var e=d.getNodes();if(0<e.length)return a.preventDefault(),e[0].selectNext(0,0),!0;}if(!require("Lexical").$isRangeSelection(d))return!1;e=a.shiftKey;return require("LexicalSelection").$shouldOverrideDefaultCharacterSelection(d,!1)?(a.preventDefault(),require("LexicalSelection").$moveCharacter(d,e,!1),!0):!1;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.KEY_BACKSPACE_COMMAND,function(a){if(K(a.target))return!1;var d=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(d))return!1;a.preventDefault();a=d.anchor;var e=a.getNode();return d.isCollapsed()&&0===a.offset&&
!require("Lexical").$isRootNode(e)&&0<require("LexicalUtils").$getNearestBlockElementAncestorOrThrow(e).getIndent()?b.dispatchCommand(require("Lexical").OUTDENT_CONTENT_COMMAND,void 0):b.dispatchCommand(require("Lexical").DELETE_CHARACTER_COMMAND,!0);},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.KEY_DELETE_COMMAND,function(a){if(K(a.target))return!1;var d=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(d))return!1;a.preventDefault();return b.dispatchCommand(require("Lexical").DELETE_CHARACTER_COMMAND,!1);},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.KEY_ENTER_COMMAND,function(a){var d=require("Lexical").$getSelection();
if(!require("Lexical").$isRangeSelection(d))return!1;if(null!==a){if((t||r||w)&&q)return!1;a.preventDefault();if(a.shiftKey)return b.dispatchCommand(require("Lexical").INSERT_LINE_BREAK_COMMAND,!1);}return b.dispatchCommand(require("Lexical").INSERT_PARAGRAPH_COMMAND,void 0);},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.KEY_ESCAPE_COMMAND,function(){var a=require("Lexical").$getSelection();if(!require("Lexical").$isRangeSelection(a))return!1;b.blur();return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.DROP_COMMAND,function(a){var _I=I(a),d=_I[1];if(0<d.length){var e=l(a.clientX,a.clientY);
if(null!==e){var _e=e,m=_e.offset,u=_e.node;var f=require("Lexical").$getNearestNodeFromDOMNode(u);if(null!==f){e=require("Lexical").$createRangeSelection();if(require("Lexical").$isTextNode(f))e.anchor.set(f.getKey(),m,"text"),e.focus.set(f.getKey(),m,"text");else{var B=f.getParentOrThrow().getKey();f=f.getIndexWithinParent()+1;e.anchor.set(B,f,"element");e.focus.set(B,f,"element");}e=require("Lexical").$normalizeSelection__EXPERIMENTAL(e);require("Lexical").$setSelection(e);}b.dispatchCommand(x,d);}a.preventDefault();return!0;}a=require("Lexical").$getSelection();return require("Lexical").$isRangeSelection(a)?!0:!1;},_require_Lexical.COMMAND_PRIORITY_EDITOR),
b.registerCommand(_require_Lexical.DRAGSTART_COMMAND,function(a){var _I2=I(a);a=_I2[0];var d=require("Lexical").$getSelection();return a&&!require("Lexical").$isRangeSelection(d)?!1:!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.DRAGOVER_COMMAND,function(a){var _I3=I(a),d=_I3[0];var e=require("Lexical").$getSelection();if(d&&!require("Lexical").$isRangeSelection(e))return!1;d=l(a.clientX,a.clientY);null!==d&&(d=require("Lexical").$getNearestNodeFromDOMNode(d.node),require("Lexical").$isDecoratorNode(d)&&a.preventDefault());return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.SELECT_ALL_COMMAND,function(){require("Lexical").$selectAll();return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),
b.registerCommand(_require_Lexical.COPY_COMMAND,function(a){require("LexicalClipboard").copyToClipboard(b,require("LexicalUtils").objectKlassEquals(a,ClipboardEvent)?a:null);return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.CUT_COMMAND,function(a){H(a,b);return!0;},_require_Lexical.COMMAND_PRIORITY_EDITOR),b.registerCommand(_require_Lexical.PASTE_COMMAND,function(a){var _I4=I(a),d=_I4[1],e=_I4[2];return 0<d.length&&!e?(b.dispatchCommand(x,d),!0):require("Lexical").isSelectionCapturedInDecoratorInput(a.target)?!1:null!==require("Lexical").$getSelection()?(G(a,b),!0):!1;},_require_Lexical.COMMAND_PRIORITY_EDITOR));};}),null);